import os
import utils

# INTERVALS
LISTEN_INTERVAL = 30
UPLOAD_INTERVAL = 60
TRANSCODE_INTERVAL = 30

# FORMAT
RECORD_FORMAT = "ts"
TRANSCODE_FORMAT = "mp4"
TIME_FORMAT = "%Y%m%d_%H%M%S"

# PATHS
PATH = "."
CONFIG_PATH = f"{PATH}/config"
RECORD_PATH = f"{PATH}/record"
TEMP_PATH = f"{RECORD_PATH}/temp"
LOG_PATH = f"{PATH}/log"
UPLOAD_LOG_PATH = f"{LOG_PATH}/upload"
BIN_PATH = f"{PATH}/venv/bin"

# UPLOAD
EXPIRATION = 1 # days

# REQUEST HEADERS
HEADERS = {}
HEADERS["Connection"] = "close"